line1=Ustawienia serwera,11
mail_system=Serwer e-mail,4,1-Sendmail,0-Postfix,2-Qmail,4-Qmail+LDAP,5-Qmail+VPOPMail,6-Exim (eksperymentalne),3-Wykryj automatycznie
line1.3=Ustawienia sieci,11
line1.4=Ustawienia interfejsu u¿ytkownika,11
line1.5=Uprawnienia administratora serwera,11
line2=Domy¶lne dla nowych domen,11
line2.1=Ustawienia SSL,11
line4=Dzia³ania podczas tworzenia serwera i u¿ytkownika,11
line4.5=Opcje Qmail+LDAP,11
line4.6=Opcje VPOPMail,11
line4.7=Opcje filtrowania spamu,11
line4.8=Polecenia przydzia³ów (Quota),11
line8=Kopia zapasowa i przywracanie,11
line6=Opcje zawaansowane,11
