#!/usr/bin/perl

=head1 exec-cmd.pl

Executed a defined custom command. The output will be as is generated by the custom command.

=cut

package virtual_server;
if (!$module_name) {
        $main::no_acl_check++;
        $ENV{'WEBMIN_CONFIG'} ||= "/etc/webmin";
        $ENV{'WEBMIN_VAR'} ||= "/var/webmin";
        if ($0 =~ /^(.*)\/[^\/]+$/) {
                chdir($pwd = $1);
        }
        else {
                chop($pwd = `pwd`);
        }
        $0 = "$pwd/exec-cmd.pl";
        require './virtual-server-lib.pl';
        $< == 0 || die "exec-cmd.pl must be run as root";
}

my $arguments = ();

while(@ARGV > 0) {
        local $a = shift(@ARGV);
        if ($a eq "--id") {
                $id=shift(@ARGV);
        }
        else {
                local $key=substr $a, 2;
                local $value=shift(@ARGV);
                $arguments{$key} = $value;
        }
}

# build up query string for execution
my $QUERY_STRING="id=$id";
foreach $key (keys %arguments)
{
        local $value=$arguments{$key};
        $QUERY_STRING="${QUERY_STRING}&$key=$value";
}

# set enviroment variables
$ENV{'WEBMIN_CONFIG'}='/etc/webmin';
$ENV{'FOREIGN_ROOT_DIRECTORY'}='/usr/share/webmin/custom';
$ENV{'FOREIGN_MODULE_NAME'}='custom';
$ENV{'REMOTE_USER'}='root';
$ENV{'QUERY_STRING'}="$QUERY_STRING";

# execute command
print(`cd /usr/share/webmin/custom/ && ./run.cgi`);

sub usage
{
        print "$_[0]\n\n" if ($_[0]);
        print "Executed a defined custom command and returns the output.\n";
        exit(1);
}
